/**
 * Enrichment Audit Logger — Appends enrichment records to a Markdown file.
 *
 * Output: `.beads/graph/enrichment-log.md`
 * Format: Markdown table with Date, Node ID, Name, Complexity, Summary.
 *
 * P-Tracker v0.11.1
 */

import { appendFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';

const LOG_HEADER = `# Enrichment Log

> Auto-generated by para-graph P-Tracker. Do not edit manually.

| Date | Node ID | Name | Complexity | Summary |
|:-----|:--------|:-----|:-----------|:--------|
`;

/**
 * Sanitize a string for safe inclusion in a Markdown table cell.
 * - Replaces `|` with `\\|` to prevent column breaks.
 * - Replaces newlines with spaces to prevent row breaks.
 */
function sanitizeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ').replace(/\r/g, '');
}

/**
 * Append an enrichment record to the audit log file.
 *
 * Creates the file with headers if it doesn't exist.
 * Thread-safe via atomic append (appendFileSync).
 *
 * @param graphDir - Path to `.beads/graph/` directory
 * @param nodeId - ID of the enriched node
 * @param nodeName - Human-readable name of the node
 * @param complexity - Complexity level assigned
 * @param summary - Summary text (will be sanitized)
 */
export function appendEnrichmentLog(
  graphDir: string,
  nodeId: string,
  nodeName: string,
  complexity: string,
  summary: string,
): void {
  const logPath = join(graphDir, 'enrichment-log.md');

  // Ensure directory exists
  if (!existsSync(dirname(logPath))) {
    mkdirSync(dirname(logPath), { recursive: true });
  }

  // Create file with header if missing
  if (!existsSync(logPath)) {
    writeFileSync(logPath, LOG_HEADER, 'utf-8');
  }

  // Build row with sanitized values
  const date = new Date().toISOString().slice(0, 19).replace('T', ' ');
  const row = `| ${date} | ${sanitizeCell(nodeId)} | ${sanitizeCell(nodeName)} | ${complexity} | ${sanitizeCell(summary)} |\n`;

  appendFileSync(logPath, row, 'utf-8');
}
